#### Task 1: Python List Calculation

In [2]:
a = [10,20,30,40,50]

for i in range(len(a)):
    a[i] += 5

print(a)

[15, 25, 35, 45, 55]


#### Task 2: Same Operation Using NumPy

In [3]:
import numpy as np

In [4]:
a = np.array([10,20,30,40,50])
# added 5 to array without using a long loop
a = a + 5

In [5]:
a

array([15, 25, 35, 45, 55])

#### Task 3: Performance Reason (Conceptual)

In [6]:
print("Numpy is faster because it uses less memory bytes than lists, thus the computer can process it fastr")

Numpy is faster because it uses less memory bytes than lists, thus the computer can process it fastr


#### Task 4: Memory Comparison

In [7]:
# array Size

a.itemsize

4

#### Task 5: Element-wise Multiplication

In [8]:
# list

x = [10,20,30]

for num in range(len(x)):
    x[num] *= 2

x

[20, 40, 60]

In [9]:
# numpy

a = np.array([[1,2],[3,4]])
a = a * 2
a

array([[2, 4],
       [6, 8]])

 #### Task 6: Invalid List Operation

In [10]:
# tried dividing a list by 2

x = x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

#### Task 7: Valid NumPy Operation

In [11]:
a = np.array([10,20,30,40,50])

a = a / 2

print(a)

[ 5. 10. 15. 20. 25.]


#### Task 8: Mixed Data Types

In [14]:
b = np.array([1.0,2,3.4])

b

# numpy converted all values in the array into floats
# if I specify a data type then it will convert the values into that data type

array([1. , 2. , 3.4])

#### Task 9: Create ndarray from List

In [22]:
c = [1,2,3,4,5]

arr = np.array(c)

print(arr)
print(type(arr ))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Task 10: Using arange()

In [27]:
array = np.arange(5,11,2) 
#(starting number, ending number, difference if you want to add any(optional))
array

array([5, 7, 9])

#### Task 11: Using zeros() and ones()

In [31]:
# creating an array of zeros
zero = np.zeros([5,])
print(zero)

# creating an array of ones
one = np.ones([5,])
print(one)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


#### Task 12: Using full()

In [37]:
full = np.full(5,7)
full

array([7, 7, 7, 7, 7])

#### Task 13: Random Array

In [46]:
rand = np.random.rand(3,)

rand

array([0.18966348, 0.1489502 , 0.37105396])

#### Task 14: Shape Attribute

In [54]:
f = np.array([[1,2,4],[3,4,5]])

print("Shape:", f.shape)

Shape: (2, 3)


 #### Task 15: Dimensions (ndim)

In [53]:
print("Number of Dimensions:", f.ndim)

Number of Dimensions: 2


#### Task 16: Size Attribute

In [57]:
g = np.array([1,2,3,4,5,6])

length = len(g)
print("Number of Elements:", length)

Number of Elements: 6


#### Task 17: Data Type (dtype)

In [61]:
print(type(g))

g.dtype

<class 'numpy.ndarray'>


dtype('int32')

#### Task 18: Item Size

In [62]:
g.itemsize

4

#### Task 19: Explicit Data Type

In [65]:
h = np.array([1,4,5,6], dtype = 'float64')
print(h)

[1. 4. 5. 6.]


#### Task 20: Type Conversion

In [66]:
g = g.astype('float64')

g

array([1., 2., 3., 4., 5., 6.])

####  Task 22: Mini Analytics Example

In [75]:
stats = ([[1,2,3,4,5],[4,5,6,7,8]])


print("Minimum:", np.min(stats))
print("Maximum:", np.max(stats))
print("Sum:", np.sum(stats))
print("Mean:", np.mean(stats))

Minimum: 1
Maximum: 8
Sum: 45
Mean: 4.5
