## 12.Array Manipulation with NumPy

#### Task 1: Create Base Array

In [45]:
import numpy as np

In [46]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

#### Task 2: Indexing (Positive Index)

In [47]:
a[1]

20

#### Task 3: Negative Indexing

In [48]:
a[-1]

50

#### Task 4: Basic Slicing

In [49]:
a[1:4]

array([20, 30, 40])

#### Task 5: Step Slicing

In [50]:
result = a[::2]
print(result)

[10 30 50]


#### Task 6: Create 2D Array

In [51]:
# creating a 2D array

b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

#### Task 7: 2D Indexing

In [52]:
b[1,1]

5

#### Task 8: Row & Column Slicing

In [53]:
print(b[0])
print(b[:,1])

[1 2 3]
[2 5]


#### Task 9: Reshape Array

In [54]:
onearray = np.array([1,2,3,4,5,6])

twoarray = onearray.reshape([3,2])
print(twoarray)

[[1 2]
 [3 4]
 [5 6]]


#### Task 10: Flatten Array

In [55]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])


new_arr = arr.flatten()
print(new_arr)

[1 2 3 4 5 2 3 4 5 6]


#### Task 11: Vertical Stack 

In [56]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

 #### Task 12: Horizontal Stack

In [57]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

#### Task 13: Column Stack

In [58]:
# will likely stack columns
stacked = np.column_stack([a,b])
print(stacked)

[[1 4]
 [2 5]
 [3 6]]


 #### Task 14: Stack with stack()

In [61]:
stack = np.stack((a,b), axis = 0)
print(stack)

[[1 2 3]
 [4 5 6]]


####  Task 15: Split Array into Equal Parts

In [62]:
# spliting array into three equal parts

arr = np.array([1,3,5,7,9,11])

new_arr = np.array_split(arr,3)

print(new_arr)

[array([1, 3]), array([5, 7]), array([ 9, 11])]


#### Task 17: Vertical Split

In [65]:
c = np.array([[1,2,3],[3,4,5],[4,5,6]])

v_split = np.vsplit((c),3)
print(v_split)

[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[4, 5, 6]])]


#### Task 18: Horizontal Split

In [66]:
c = np.array([[1,2,3],[3,4,5],[4,5,6]])

h_split = np.hsplit((c),3)
print(h_split)

[array([[1],
       [3],
       [4]]), array([[2],
       [4],
       [5]]), array([[3],
       [5],
       [6]])]


#### Task 19: Element-wise Addition

In [68]:
d = c + 10
print(d)

[[11 12 13]
 [13 14 15]
 [14 15 16]]


#### Task 20: Element-wise Multiplication

In [69]:
e = c * d
print(e)

[[11 24 39]
 [39 56 75]
 [56 75 96]]


 #### Task 21: Conditional Vectorized Operation


In [75]:
bool_arr = np.array([10,65,30,45,50,65,70,85])

bool_arr > 50
    

array([False,  True, False, False, False,  True,  True,  True])

 #### Task 22: Vectorized Filtering

In [77]:
bool_arr[bool_arr > 30]

array([65, 45, 50, 65, 70, 85])