# 13.Statistical Analysis with NumPy

#### Task 1: Create Base Dataset

In [36]:
import numpy as np

In [37]:
base_data = np.array([10, 20, 30, 40, 50])
base_data

array([10, 20, 30, 40, 50])

#### Task 2: Sum of Values

In [38]:
print("Sum:",np.sum(base_data))

Sum: 150


 #### Task 3: Mean (Average)

In [39]:
print("Mean:", np.mean(base_data))

Mean: 30.0


#### Task 4 : Median

In [40]:
print("Median:", np.median(base_data))

Median: 30.0


#### Task 5 : Standard Deviation

In [41]:
print("Standard Deviation:", np.std(base_data))

Standard Deviation: 14.142135623730951


#### Sample Data

In [42]:
data = np.array([
    [10, 20, 30],
    [45, 55, 65]
])

#### Task 6: Total Sum of All Elements

In [43]:
print("Total Sum:", np.sum(data))

Total Sum: 225


#### Task 7: Row-wise Sum 

In [44]:
np.sum(data, axis = 1)

array([ 60, 165])

#### Task 8: Column-wise Sum (axis=0)

In [45]:
np.sum(data, axis = 0)

array([55, 75, 95])

 #### Task 9: Row-wise Mean

In [46]:
np.mean(data, axis = 1)

array([20., 55.])

 #### Task 9: Column-wise Mean

In [47]:
np.mean(data, axis = 0)

array([27.5, 37.5, 47.5])

 #### Task 9: Column-wise Standard Deviation

In [48]:
np.std(data, axis = 0)

array([17.5, 17.5, 17.5])

#### Sample Dataset:  MEDIAN & REALISTIC DATA DISTRIBUTION

In [49]:

scores = np.array([50, 30, 85, 77, 95])

#### Task 12: Mean vs Median

In [50]:
mean = np.mean(scores)
median = np.median(scores)

print("Mean:",mean)
print("Median:",median)

Mean: 67.4
Median: 77.0


#### Task 13: Outlier Impact Observation

In [51]:
scores_new = np.array([50, 30, 85, 77])

mean_new = np.mean(scores_new)
median_new = np.median(scores_new)

print("Mean:",mean_new)
print("Median:",median_new)

Mean: 60.5
Median: 63.5


#### Task 14: Scalar Broadcasting

In [52]:
arr = np.array([10,20,30,40,50])

In [53]:
arr + 10

array([20, 30, 40, 50, 60])

#### Task 15: Vector Broadcasting

In [58]:
twoarr = ([[1,2,3],[4,5,6]])

onearr = np.array([1,2,3])

result = twoarr + onearr
print(result)


[[2 4 6]
 [5 7 9]]


#### Task 16: Column Broadcasting

In [60]:
col_mean = np.mean(data, axis=0)

result = data - col_mean

print(result)

[[-15. -15. -15.]
 [ 15.  15.  15.]]


####  Task 18: Loop-based Mean Calculation

In [62]:
numbers = [10, 20, 30, 40, 50]

total = 0
count = 0

for num in numbers:
    total += num
    count += 1

mean = total / count

print(f"Mean calculated using loop: {mean}")


Mean calculated using loop: 30.0


####  Task 19: NumPy Vectorized Mean

In [65]:
numbers = np.array([10, 20, 30, 40, 50])

mean_arr = np.mean(numbers)
mean_arr

30.0

#### Task 21: Sales Analytics Summary

In [66]:
sales_data = np.array([5000, 8500, 12000, 3000, 7000])

In [69]:
print("Total:", np.sum(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))

greater = sales_data[sales_data > np.mean(sales_data)]
print("Above Average Sales:", greater)

Total: 35500
Mean: 7100.0
Median: 7000.0
Standard Deviation: 3072.458299147443
Above Average Sales: [ 8500 12000]
