# Numpy

In [2]:
import numpy as np


### Basics

In [3]:
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [4]:
b = np.array([[0.1,0.2],[0.34,0.99]])
print(b)

[[0.1  0.2 ]
 [0.34 0.99]]


In [5]:
# Get the dimensions
a.ndim
b.ndim

2

In [6]:
# Get shape
a.shape


(3,)

In [7]:
b.shape

(2, 2)

In [8]:
# Get data type
a.dtype

dtype('int16')

In [9]:
a.itemsize

2

In [10]:
b.dtype

dtype('float64')

In [11]:
# Get size
b.itemsize

8

### Accessing, Changing specific elements, rows, columns etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [14]:
# Get a specific element [row, columm]

a[1,4]

12

In [15]:
# getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# getting a specific column
a[:,3]

array([ 4, 11])

In [17]:
# lets get a little fancy
# lets access row 1, start index 1, endindex 6, diff 2)

a[0, 1:6:2]

array([2, 4, 6])

In [18]:
# changing a specific element in the array

a[1,3] = 12

In [19]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 12 12 13 14]]


#### 3D example

In [20]:
c = np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [21]:
c.ndim


3

In [22]:
#getting a specific element in a 3D array (work outside in)

#let get 3

c[0,1,0]

3

In [23]:
#replacing an array within
c[:,2,:] = [[4,5]]

In [24]:
c

array([[[1, 2],
        [3, 4],
        [4, 5]]])

### Initializing Different Types of Array

In [25]:
# initializing an all 0s matrix
np.zeros((2,3,4)) #(dimenions,rows,columns)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
# initializing an all 1 matrix
np.ones((3,4,1))

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [27]:
# random decimal values
np.random.rand(5,2)

array([[0.69036337, 0.89349931],
       [0.00294147, 0.52677125],
       [0.52353996, 0.67502329],
       [0.55892574, 0.41464805],
       [0.01759609, 0.35711228]])

In [28]:
# random integer values
np.random.randint(0,10, size = (2,3))
#(starting number, ending number is exclusive, and then specify the shape of the array that you want to create)

array([[8, 0, 2],
       [6, 4, 0]])

In [29]:
# identity matrix is a square matrix with n rows and n columns, n is the parameter that you pass
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#repeating an array
arr = np.array([[1,2,3,4]])

rep = np.repeat(arr,2, axis = 0)

print(rep)

[[1 2 3 4]
 [1 2 3 4]]


In [45]:
#creating a specific array
output = np.ones((5,5))
print(output)

zero = np.zeros((3,3))
print(zero)

zero[1,1] = 9
print(zero)

output[1:4,1:4] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### BE CAREFUL WHEN YOU COPY ARRAYS

In [48]:
c = np.array([1,2,3])

b = c.copy()

c
b[2] = 1
b

array([1, 2, 1])

#### Mathematics

In [49]:
d = np.array([1,2,3,4])

print(d)

[1 2 3 4]


In [50]:
d + 2

array([3, 4, 5, 6])

In [51]:
d * 2

array([2, 4, 6, 8])

In [52]:
d ** 2

array([ 1,  4,  9, 16])

In [55]:
# adding two different arrays

e = np.array([2,3,4,5])

e + d

array([3, 5, 7, 9])

In [56]:
# you can also perform trignometric functions
np.sin(d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [58]:
np.cos(e)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

##### Linear Algebra

In [59]:
# matrix multiplication just like in linear algebra
a = np.ones((3,4))
print(a)

b = np.full((4,3),2)
print(b)

# the row number of the first array should be the same as the column number for the second array for the matrix multiplication to work
np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

#### Statistics

In [60]:
stats = np.array([[2,3,4],[5,6,7]])
stats

array([[2, 3, 4],
       [5, 6, 7]])

In [61]:
# minimum value of an array
np.min(stats)

2

In [62]:
# maximum value of an array
np.max(stats)

7

In [63]:
# sum of the entire array and you can also specify an axis
np.sum(stats, axis = 0)

array([ 7,  9, 11])

#### Reorganzing Arrays

In [64]:
# reshaping an array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# reshaping changed its number of rows and columns to what you specified and what is feasible

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [65]:
# vertically stacking array
v1 = np.array([1,2,3,4])
v2 = np.array([3,4,5,6])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [66]:
#Horizontally stacking arrays

h1 = np.array([2,3,4,5])
h2 = np.array([2,4,6,8])

np.hstack([h1,h2,h2])

array([2, 3, 4, 5, 2, 4, 6, 8, 2, 4, 6, 8])

#### Miscellaneous

In [67]:
filedata = np.genfromtxt('data.txt' , delimiter = ",")

filedata = filedata.astype('int32')

filedata

# condition: has to have the same number of columns for each dimension

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9,  8],
       [ 3,  4,  5,  6,  7,  8,  9,  8,  7],
       [ 4,  5,  6,  7,  8,  9, 12,  3,  1]])