# Retail Chain Sales Analytics Assignment

In [2]:
import numpy as np

In [3]:
# we will generate sales recordss 

np.random.seed(42)

n = 10000


store_id = np.random.randint(1, 21, n)
product_id = np.random.randint(100, 200, n)     # Product ID
category_id = np.random.randint(1, 6, n)       # Category ID
quantity = np.random.randint(1, 10, n)     # Quantity
price = np.random.uniform(100, 1000, n)    # Price
discount = np.random.uniform(0, 30, n)        # Discount %
customer_age = np.random.randint(18, 65, n)       # Customer Age
rating = np.random.uniform(1, 5, n)        # Rating
doy = np.random.randint(1, 366, n)        # Day of year

sales_data =np.column_stack((store_id, product_id, category_id, quantity, price, discount, customer_age, rating, doy))
    
print(sales_data)

[[  7.         162.           1.         ...  21.           2.26425138
  209.        ]
 [ 20.         186.           5.         ...  41.           4.38196762
  228.        ]
 [ 15.         140.           2.         ...  31.           3.35167174
  185.        ]
 ...
 [  2.         185.           5.         ...  24.           4.17935394
  275.        ]
 [  1.         171.           2.         ...  28.           2.13588797
  338.        ]
 [  2.         197.           5.         ...  48.           3.03901003
  237.        ]]


#### Generate some basic info

In [4]:
sales_data.ndim

2

In [5]:
sales_data.shape

(10000, 9)

In [6]:
sales_data.dtype

dtype('float64')

In [7]:
sales_data.itemsize

8

In [10]:
# inserted missing values to create a data set with NaN values so that we can clean it
mask = np.random.choice([0,1], size=sales_data.shape, p=[0.98, 0.02])
data_with_nan = sales_data.copy()
data_with_nan[mask == 1] = np.nan

data_with_nan

array([[  7.        , 162.        ,   1.        , ...,  21.        ,
          2.26425138, 209.        ],
       [ 20.        , 186.        ,   5.        , ...,  41.        ,
          4.38196762, 228.        ],
       [ 15.        , 140.        ,   2.        , ...,  31.        ,
          3.35167174, 185.        ],
       ...,
       [  2.        , 185.        ,   5.        , ...,  24.        ,
          4.17935394, 275.        ],
       [  1.        , 171.        ,   2.        , ...,  28.        ,
          2.13588797, 338.        ],
       [  2.        , 197.        ,   5.        , ...,  48.        ,
          3.03901003, 237.        ]])

In [13]:
price_col = 4

nanmedian = np.nanmedian(data_with_nan[:, price_col])
nanmedian

549.8609156069842

In [14]:
data_with_nan[np.isnan(data_with_nan[:,price_col]),price_col] = nanmedian

In [15]:
clean_data = data_with_nan[~np.isnan(data_with_nan[:, 3])]

In [16]:
clean_data

array([[  7.        , 162.        ,   1.        , ...,  21.        ,
          2.26425138, 209.        ],
       [ 20.        , 186.        ,   5.        , ...,  41.        ,
          4.38196762, 228.        ],
       [ 15.        , 140.        ,   2.        , ...,  31.        ,
          3.35167174, 185.        ],
       ...,
       [  2.        , 185.        ,   5.        , ...,  24.        ,
          4.17935394, 275.        ],
       [  1.        , 171.        ,   2.        , ...,  28.        ,
          2.13588797, 338.        ],
       [  2.        , 197.        ,   5.        , ...,  48.        ,
          3.03901003, 237.        ]])

## Revenue Per Transaction

In [29]:


quantity = clean_data[:, 3]
price = clean_data[:, 4]
discount = clean_data[:, 5]

revenue = quantity * price * (1 - discount/100)

revenue

array([4710.96278761,           nan, 3681.3560062 , ..., 6193.62218502,
       2630.97073757, 2855.17359036])

In [30]:
clean_data = np.column_stack((clean_data, revenue))


In [31]:
clean_data

array([[7.00000000e+00, 1.62000000e+02, 1.00000000e+00, ...,
        2.09000000e+02, 4.71096279e+03, 4.71096279e+03],
       [2.00000000e+01, 1.86000000e+02, 5.00000000e+00, ...,
        2.28000000e+02,            nan,            nan],
       [1.50000000e+01, 1.40000000e+02, 2.00000000e+00, ...,
        1.85000000e+02, 3.68135601e+03, 3.68135601e+03],
       ...,
       [2.00000000e+00, 1.85000000e+02, 5.00000000e+00, ...,
        2.75000000e+02, 6.19362219e+03, 6.19362219e+03],
       [1.00000000e+00, 1.71000000e+02, 2.00000000e+00, ...,
        3.38000000e+02, 2.63097074e+03, 2.63097074e+03],
       [2.00000000e+00, 1.97000000e+02, 5.00000000e+00, ...,
        2.37000000e+02, 2.85517359e+03, 2.85517359e+03]])

In [32]:
age = clean_data[:, 6]

age_group = np.select(
    [
        age <= 25,
        (age > 25) & (age <= 40),
        (age > 40) & (age <= 60),
        age > 60
    ],
    [1, 2, 3, 4]
)


In [33]:
age_group

array([1, 3, 2, ..., 1, 2, 3])

## High Value Customers

In [34]:
high_value = clean_data[
    (clean_data[:, -1] > 5000) &
    (clean_data[:, 7] > 4)
]


In [35]:
high_value

array([[1.20000000e+01, 1.73000000e+02, 2.00000000e+00, ...,
        2.74000000e+02, 5.88018952e+03, 5.88018952e+03],
       [1.40000000e+01, 1.13000000e+02, 2.00000000e+00, ...,
        1.90000000e+01, 5.66600008e+03, 5.66600008e+03],
       [2.00000000e+01, 1.06000000e+02, 4.00000000e+00, ...,
        2.77000000e+02, 6.06704163e+03, 6.06704163e+03],
       ...,
       [2.00000000e+01, 1.89000000e+02, 5.00000000e+00, ...,
        1.99000000e+02, 5.25164202e+03, 5.25164202e+03],
       [4.00000000e+00, 1.31000000e+02, 3.00000000e+00, ...,
        1.50000000e+01, 6.14958361e+03, 6.14958361e+03],
       [2.00000000e+00, 1.85000000e+02, 5.00000000e+00, ...,
        2.75000000e+02, 6.19362219e+03, 6.19362219e+03]])

## Total Revenue Per Store

In [36]:
stores = np.unique(clean_data[:, 0])

store_revenue = np.array([
    clean_data[clean_data[:, 0] == s][:, -1].sum()
    for s in stores
])

## Category-wise Revenue

In [37]:
categories = np.unique(clean_data[:, 2])

category_revenue = np.array([
    clean_data[clean_data[:, 2] == c][:, -1].sum()
    for c in categories
])


## Correlation Between Price & Quantity

In [40]:
np.corrcoef(clean_data[:, 4], clean_data[:, 3])

array([[1.        , 0.01994434],
       [0.01994434, 1.        ]])

## Sort by Revenue

In [41]:
sorted_data = clean_data[clean_data[:, -1].argsort()]
sorted_data

array([[ 16.        , 151.        ,   5.        , ..., 270.        ,
         79.26124236,  79.26124236],
       [ 10.        , 159.        ,   1.        , ...,  83.        ,
         82.82922244,  82.82922244],
       [  8.        , 140.        ,   3.        , ..., 170.        ,
         82.83779973,  82.83779973],
       ...,
       [  5.        , 105.        ,   3.        , ...,   2.        ,
                 nan,          nan],
       [ 15.        , 110.        ,   1.        , ..., 113.        ,
                 nan,          nan],
       [ 15.        , 163.        ,   1.        , ..., 344.        ,
                 nan,          nan]])

## Top 10 Transactions

In [42]:
top10 = clean_data[np.argsort(clean_data[:, -1])[-10:]]

In [43]:
top10

array([[  5.        ,          nan,   2.        ,   3.        ,
        369.34885691,          nan,  49.        ,   2.09461676,
        126.        ,          nan,          nan],
       [ 16.        , 144.        ,   3.        ,   6.        ,
        180.58158741,          nan,  40.        ,   4.26690392,
        217.        ,          nan,          nan],
       [ 19.        , 186.        ,   2.        ,   3.        ,
        297.2362352 ,          nan,  54.        ,   1.72937495,
        342.        ,          nan,          nan],
       [ 14.        , 152.        ,   2.        ,   1.        ,
        254.69897455,          nan,  25.        ,   3.20232178,
         30.        ,          nan,          nan],
       [  7.        , 186.        ,   4.        ,   9.        ,
        549.86091561,          nan,  46.        ,   4.6301137 ,
        251.        ,          nan,          nan],
       [  2.        , 172.        ,   4.        ,   9.        ,
        902.42676545,          nan,      